/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Semantic tokens wired to CSS variables (see index.css)
        'page': 'rgb(var(--ds-bg) / <alpha-value>)',
        'background': 'rgb(var(--ds-bg) / <alpha-value>)',
        'surface': 'rgb(var(--ds-surface) / <alpha-value>)',
        'surface-light': 'rgb(var(--ds-surface-light) / <alpha-value>)',
        'surface-lowest': 'rgb(var(--ds-surface-lowest) / <alpha-value>)',
        'surface-low': 'rgb(var(--ds-surface-low) / <alpha-value>)',
        'card': 'rgb(var(--ds-surface) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--ds-surface-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--ds-surface-low) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--ds-surface-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--ds-surface-highest) / <alpha-value>)',
        'surface-bright': 'rgb(var(--ds-surface) / <alpha-value>)',
        'surface-tint': 'rgb(var(--ds-primary) / <alpha-value>)',
        'surface-variant': 'rgb(var(--ds-surface-light) / <alpha-value>)',
        'surface-container': 'rgb(var(--ds-surface-low) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--ds-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--ds-inverse-on-surface) / <alpha-value>)',
        'outline': 'rgb(var(--ds-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--ds-border) / <alpha-value>)',
        'on-surface': 'rgb(var(--ds-text) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--ds-text-secondary) / <alpha-value>)',
        'on-background': 'rgb(var(--ds-text) / <alpha-value>)',
        'on-background-variant': 'rgb(var(--ds-text-secondary) / <alpha-value>)',
        'accent': 'rgb(var(--ds-accent) / <alpha-value>)',
        'accent-container': 'rgb(var(--ds-primary-container) / <alpha-value>)',
        'on-accent': 'rgb(var(--ds-on-primary) / <alpha-value>)',
        'primary': 'rgb(var(--ds-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--ds-primary-container) / <alpha-value>)',
        'on-primary': 'rgb(var(--ds-on-primary) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--ds-on-primary-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--ds-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--ds-primary-fixed-dim) / <alpha-value>)',
        'secondary': 'rgb(var(--ds-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--ds-secondary-container) / <alpha-value>)',
        'on-secondary': 'rgb(var(--ds-on-secondary) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--ds-on-secondary-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--ds-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--ds-secondary-fixed-dim) / <alpha-value>)',
        'tertiary': 'rgb(var(--ds-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--ds-tertiary-container) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--ds-on-tertiary) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--ds-on-tertiary-container) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--ds-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--ds-tertiary-fixed-dim) / <alpha-value>)',
        'error': 'rgb(var(--ds-error) / <alpha-value>)',
        'error-container': 'rgb(var(--ds-error-container) / <alpha-value>)',
        'on-error': 'rgb(var(--ds-on-error) / <alpha-value>)',
        'on-error-container': 'rgb(var(--ds-on-error-container) / <alpha-value>)',
        'border-outline-variant': 'rgb(var(--ds-border) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        'display': ['Barlow Condensed', 'Chakra Petch', 'sans-serif'],
        'stamp': ['Chakra Petch', 'Barlow Condensed', 'sans-serif'],
        'body': ['Plus Jakarta Sans', 'sans-serif'],
        'label': ['Barlow Condensed', 'Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Barlow Condensed', 'sans-serif'],
        'headline-md': ['Barlow Condensed', 'sans-serif'],
        'headline-lg-mobile': ['Barlow Condensed', 'sans-serif'],
        'mono': ['Courier Prime', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'display-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-xs': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        xs: '0.25rem',
        gutter: '1.5rem',
        xl: '2.5rem',
        'margin-desktop': '2rem',
        md: '1rem',
        lg: '1.5rem',
        'margin-mobile': '1rem',
        sm: '0.5rem',
        base: '4px',
      },
    },
  },
  plugins: [],
}
